const featureCatalog = Object.freeze([
    {
        code: 'DASHBOARD_VISUALIZAR',
        name: 'Visualizar dashboard',
        description: 'Permite acessar o painel inicial com indicadores e agenda de contatos.',
        module: 'Dashboard',
        location: 'Inicio',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: true,
        permissionControlled: false
    },
    {
        code: 'AGENDA_VISUALIZAR',
        name: 'Visualizar agenda de contatos',
        description: 'Permite visualizar contatos atrasados, contatos para hoje, contatos realizados hoje e proximos contatos.',
        module: 'Agenda',
        location: 'Inicio > Agenda de contatos',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: false
    },
    {
        code: 'AGENDA_CONTATO_REGISTRAR',
        name: 'Registrar contato',
        description: 'Permite registrar historico de contato, dados do atendimento, beneficios e proximo contato de uma empresa.',
        module: 'Agenda',
        location: 'Inicio > Empresa selecionada > Historico',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: false
    },
    {
        code: 'EMPRESA_VISUALIZAR',
        name: 'Visualizar empresas',
        description: 'Permite pesquisar e visualizar empresas cadastradas ou encontradas na base de pesquisa.',
        module: 'Empresa',
        location: 'Inicio > Empresas',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: true,
        permissionControlled: false
    },
    {
        code: 'EMPRESA_CADASTRAR',
        name: 'Cadastrar empresa',
        description: 'Permite cadastrar manualmente uma empresa no CRM.',
        module: 'Empresa',
        location: 'Empresas > Cadastrar empresas',
        route: '#empresas/cadastrar',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: true,
        permissionControlled: false
    },
    {
        code: 'EMPRESA_IMPORTAR',
        name: 'Importar empresas',
        description: 'Permite importar empresas por arquivos CSV ou XLSX e consultar o historico de importacoes.',
        module: 'Empresa',
        location: 'Empresas > Importacao',
        route: '#empresas/importacao',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: true,
        permissionControlled: false
    },
    {
        code: 'EMPRESA_FLAG_ALTERAR',
        name: 'Alterar flag da empresa',
        description: 'Permite marcar ou remover a flag de acompanhamento de uma empresa.',
        module: 'Empresa',
        location: 'Inicio > Tabela de empresas',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: false
    },
    {
        code: 'PESQUISA_AVANCADA',
        name: 'Pesquisa avancada',
        description: 'Permite pesquisar empresas com filtros por nome fantasia, UF, municipio, CNAE, abertura e filtros rapidos.',
        module: 'Pesquisa',
        location: 'Empresas > Pesquisa avancada',
        route: '#pesquisa-avancada',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: true,
        permissionControlled: false
    },
    {
        code: 'PESQUISA_RFB',
        name: 'Pesquisa CNPJ',
        description: 'Permite pesquisar empresas na base principal ou no servico de pesquisa configurado.',
        module: 'Pesquisa',
        location: 'Inicio > Pesquisa CNPJ',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: false
    },
    {
        code: 'EMPRESA_EXPORTAR',
        name: 'Exportar empresas selecionadas',
        description: 'Permite exportar empresas selecionadas para planilha.',
        module: 'Empresa',
        location: 'Inicio > Tabela de empresas',
        route: '#inicio',
        permission: null,
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: false
    },
    {
        code: 'USUARIO_VISUALIZAR',
        name: 'Visualizar usuarios',
        description: 'Permite listar usuarios da propria organizacao.',
        module: 'Usuario',
        location: 'Administracao > Usuarios',
        route: '/api/admin/users',
        permission: 'USUARIO_VISUALIZAR',
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: true
    },
    {
        code: 'USUARIO_CADASTRAR',
        name: 'Cadastrar usuarios',
        description: 'Permite criar usuarios na propria organizacao.',
        module: 'Usuario',
        location: 'Administracao > Usuarios',
        route: '/api/admin/users',
        permission: 'USUARIO_CADASTRAR',
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: true
    },
    {
        code: 'PERFIL_VISUALIZAR',
        name: 'Visualizar perfis',
        description: 'Permite consultar perfis disponiveis da propria organizacao.',
        module: 'Perfil',
        location: 'Administracao > Perfis',
        route: '/api/admin/profiles',
        permission: 'PERFIL_VISUALIZAR',
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: true
    },
    {
        code: 'PERMISSAO_VISUALIZAR',
        name: 'Visualizar permissoes',
        description: 'Permite consultar permissoes sincronizadas com o catalogo oficial de funcionalidades.',
        module: 'Permissao',
        location: 'Administracao > Permissoes',
        route: '/api/admin/permissions',
        permission: 'PERMISSAO_VISUALIZAR',
        addedInVersion: '1.0.0',
        lastRelevantChangeVersion: '1.0.0',
        status: 'active',
        appearsInMenu: false,
        permissionControlled: true
    }
]);

module.exports = featureCatalog;
